### PR TITLE
Fix entry point typo

### PR DESCRIPTION
**Pull request by wshanks**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wshanks** [comment]
@conda-forge-admin, please rerender

**Comment by wshanks** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
Hi @wshanks fancy seeing you here 😄
If you want, feel free to add yourself to this feedstock as well since you're also in Qiskit.

**Comment by wshanks** [comment]
Okay, I will. Does this one have a direct connection to a Qiskit project? I was interested in it for testing rustworkx and qiskit which build abi3 extensions but I didn't know it was required for anything.

**Comment by BastianZim** [comment]
No, I don't think so. Just for the testing that you are doing. Should help you iterate faster in case I'm away.

**Pull request merged**
